/*
 * This source file was generated by the Gradle 'init' task
 */
package stockstalker;

import java.util.HashMap;
import java.util.Scanner;

import stockstalker.worker.StockStalker;

public class App {

    public static void main(String[] args) {
       
        //Get the stock and the price they want to be alerted at 
        Scanner scanner = new Scanner(System.in);

        System.out.println("How many stocks would you like to keep track of ");
        int numOfStock = scanner.nextInt();
        scanner.nextLine();
        HashMap<String, Integer> stockNames = new HashMap<>();
        for(int i = 0; i < numOfStock; i++){
            int j = i + 1;
            System.out.println("What is the name of " + j + " stock you would like to track");
            String stockName =scanner.nextLine();
            System.out.println("What price would you like to be notified at ");
            int price = scanner.nextInt();
            scanner.nextLine();
            stockNames.put(stockName, price);
        }
        int threadNum = 1;
        for (HashMap.Entry<String, Integer> entry : stockNames.entrySet()) {
            String stockName = entry.getKey();
            Integer price = entry.getValue();
            StockStalker stockStalker = new StockStalker(threadNum, stockName, price);
            threadNum++;
            stockStalker.start();
        }
        scanner.close();
        System.out.println("Congrats you are now multhreading");

    }
}
